name: google_fonts_cyrillic_ext_lite
description: Cyrillic Extended fonts by google right into your Flutter application. Contains only regular styles of fonts. Taken from https:&#x2F;&#x2F;fonts.google.com.
version: 0.1.0
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Alegreya
      fonts:
        - asset: lib/fonts/Alegreya/Alegreya-Regular.ttf
          weight: 400
    - family: AlegreyaSans
      fonts:
        - asset: lib/fonts/Alegreya_Sans/AlegreyaSans-Regular.ttf
          weight: 400
    - family: AlegreyaSansSC
      fonts:
        - asset: lib/fonts/Alegreya_Sans_SC/AlegreyaSansSC-Regular.ttf
          weight: 400
    - family: AlegreyaSC
      fonts:
        - asset: lib/fonts/Alegreya_SC/AlegreyaSC-Regular.ttf
          weight: 400
    - family: Alice
      fonts:
        - asset: lib/fonts/Alice/Alice-Regular.ttf
          weight: 400
    - family: Andika
      fonts:
        - asset: lib/fonts/Andika/Andika-Regular.ttf
          weight: 400
    - family: Arimo
      fonts:
        - asset: lib/fonts/Arimo/Arimo-Regular.ttf
          weight: 400
    - family: Arsenal
      fonts:
        - asset: lib/fonts/Arsenal/Arsenal-Regular.ttf
          weight: 400
    - family: Caveat
      fonts:
        - asset: lib/fonts/Caveat/Caveat-Regular.ttf
          weight: 400
    - family: Comfortaa
      fonts:
        - asset: lib/fonts/Comfortaa/Comfortaa-Regular.ttf
          weight: 400
    - family: Cormorant
      fonts:
        - asset: lib/fonts/Cormorant/Cormorant-Regular.ttf
          weight: 400
    - family: CormorantGaramond
      fonts:
        - asset: lib/fonts/Cormorant_Garamond/CormorantGaramond-Regular.ttf
          weight: 400
    - family: CormorantInfant
      fonts:
        - asset: lib/fonts/Cormorant_Infant/CormorantInfant-Regular.ttf
          weight: 400
    - family: CormorantSC
      fonts:
        - asset: lib/fonts/Cormorant_SC/CormorantSC-Regular.ttf
          weight: 400
    - family: CormorantUnicase
      fonts:
        - asset: lib/fonts/Cormorant_Unicase/CormorantUnicase-Regular.ttf
          weight: 400
    - family: Cousine
      fonts:
        - asset: lib/fonts/Cousine/Cousine-Regular.ttf
          weight: 400
    - family: Cuprum
      fonts:
        - asset: lib/fonts/Cuprum/Cuprum-Regular.ttf
          weight: 400
    - family: DidactGothic
      fonts:
        - asset: lib/fonts/Didact_Gothic/DidactGothic-Regular.ttf
          weight: 400
    - family: EBGaramond
      fonts:
        - asset: lib/fonts/EB_Garamond/EBGaramond-Regular.ttf
          weight: 400
    - family: FiraCode
      fonts:
        - asset: lib/fonts/Fira_Code/FiraCode-Regular.ttf
          weight: 400
    - family: FiraMono
      fonts:
        - asset: lib/fonts/Fira_Mono/FiraMono-Regular.ttf
          weight: 400
    - family: FiraSans
      fonts:
        - asset: lib/fonts/Fira_Sans/FiraSans-Regular.ttf
          weight: 400
    - family: FiraSansCondensed
      fonts:
        - asset: lib/fonts/Fira_Sans_Condensed/FiraSansCondensed-Regular.ttf
          weight: 400
    - family: FiraSansExtraCondensed
      fonts:
        - asset: lib/fonts/Fira_Sans_Extra_Condensed/FiraSansExtraCondensed-Regular.ttf
          weight: 400
    - family: Forum
      fonts:
        - asset: lib/fonts/Forum/Forum-Regular.ttf
          weight: 400
    - family: Gabriela
      fonts:
        - asset: lib/fonts/Gabriela/Gabriela-Regular.ttf
          weight: 400
    - family: IBMPlexMono
      fonts:
        - asset: lib/fonts/IBM_Plex_Mono/IBMPlexMono-Regular.ttf
          weight: 400
    - family: IBMPlexSans
      fonts:
        - asset: lib/fonts/IBM_Plex_Sans/IBMPlexSans-Regular.ttf
          weight: 400
    - family: IBMPlexSerif
      fonts:
        - asset: lib/fonts/IBM_Plex_Serif/IBMPlexSerif-Regular.ttf
          weight: 400
    - family: IstokWeb
      fonts:
        - asset: lib/fonts/Istok_Web/IstokWeb-Regular.ttf
          weight: 400
    - family: Jura
      fonts:
        - asset: lib/fonts/Jura/Jura-Regular.ttf
          weight: 400
    - family: Kurale
      fonts:
        - asset: lib/fonts/Kurale/Kurale-Regular.ttf
          weight: 400
    - family: Lobster
      fonts:
        - asset: lib/fonts/Lobster/Lobster-Regular.ttf
          weight: 400
    - family: Lora
      fonts:
        - asset: lib/fonts/Lora/Lora-Regular.ttf
          weight: 400
    - family: MPLUS1p
      fonts:
        - asset: lib/fonts/M_PLUS_1p/MPLUS1p-Regular.ttf
          weight: 400
    - family: MPLUSRounded1c
      fonts:
        - asset: lib/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Regular.ttf
          weight: 400
    - family: Merriweather
      fonts:
        - asset: lib/fonts/Merriweather/Merriweather-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat/Montserrat-Regular.ttf
          weight: 400
    - family: MontserratAlternates
      fonts:
        - asset: lib/fonts/Montserrat_Alternates/MontserratAlternates-Regular.ttf
          weight: 400
    - family: NotoSans
      fonts:
        - asset: lib/fonts/Noto_Sans/NotoSans-Regular.ttf
          weight: 400
    - family: NotoSerif
      fonts:
        - asset: lib/fonts/Noto_Serif/NotoSerif-Regular.ttf
          weight: 400
    - family: OldStandardTT
      fonts:
        - asset: lib/fonts/Old_Standard_TT/OldStandardTT-Regular.ttf
          weight: 400
    - family: OpenSans
      fonts:
        - asset: lib/fonts/Open_Sans/OpenSans-Regular.ttf
          weight: 400
    - family: OpenSansCondensed
      fonts:
        - asset: lib/fonts/Open_Sans_Condensed/OpenSansCondensed-Light.ttf
          weight: 300
    - family: Oranienbaum
      fonts:
        - asset: lib/fonts/Oranienbaum/Oranienbaum-Regular.ttf
          weight: 400
    - family: Oswald
      fonts:
        - asset: lib/fonts/Oswald/Oswald-Regular.ttf
          weight: 400
    - family: Pacifico
      fonts:
        - asset: lib/fonts/Pacifico/Pacifico-Regular.ttf
          weight: 400
    - family: Pangolin
      fonts:
        - asset: lib/fonts/Pangolin/Pangolin-Regular.ttf
          weight: 400
    - family: Philosopher
      fonts:
        - asset: lib/fonts/Philosopher/Philosopher-Regular.ttf
          weight: 400
    - family: Play
      fonts:
        - asset: lib/fonts/Play/Play-Regular.ttf
          weight: 400
    - family: Podkova
      fonts:
        - asset: lib/fonts/Podkova/Podkova-Regular.ttf
          weight: 400
    - family: Prata
      fonts:
        - asset: lib/fonts/Prata/Prata-Regular.ttf
          weight: 400
    - family: PressStart2P
      fonts:
        - asset: lib/fonts/Press_Start_2P/PressStart2P-Regular.ttf
          weight: 400
    - family: PTMono
      fonts:
        - asset: lib/fonts/PT_Mono/PTMono-Regular.ttf
          weight: 400
    - family: PTSans
      fonts:
        - asset: lib/fonts/PT_Sans/PTSans-Regular.ttf
          weight: 400
    - family: PTSansCaption
      fonts:
        - asset: lib/fonts/PT_Sans_Caption/PTSansCaption-Regular.ttf
          weight: 400
    - family: PTSansNarrow
      fonts:
        - asset: lib/fonts/PT_Sans_Narrow/PTSansNarrow-Regular.ttf
          weight: 400
    - family: PTSerif
      fonts:
        - asset: lib/fonts/PT_Serif/PTSerif-Regular.ttf
          weight: 400
    - family: PTSerifCaption
      fonts:
        - asset: lib/fonts/PT_Serif_Caption/PTSerifCaption-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: lib/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
    - family: RobotoCondensed
      fonts:
        - asset: lib/fonts/Roboto_Condensed/RobotoCondensed-Regular.ttf
          weight: 400
    - family: RobotoMono
      fonts:
        - asset: lib/fonts/Roboto_Mono/RobotoMono-Regular.ttf
          weight: 400
    - family: RobotoSlab
      fonts:
        - asset: lib/fonts/Roboto_Slab/RobotoSlab-Regular.ttf
          weight: 400
    - family: Scada
      fonts:
        - asset: lib/fonts/Scada/Scada-Regular.ttf
          weight: 400
    - family: SourceCodePro
      fonts:
        - asset: lib/fonts/Source_Code_Pro/SourceCodePro-Regular.ttf
          weight: 400
    - family: SourceSansPro
      fonts:
        - asset: lib/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
          weight: 400
    - family: Tinos
      fonts:
        - asset: lib/fonts/Tinos/Tinos-Regular.ttf
          weight: 400
    - family: Ubuntu
      fonts:
        - asset: lib/fonts/Ubuntu/Ubuntu-Regular.ttf
          weight: 400
    - family: UbuntuCondensed
      fonts:
        - asset: lib/fonts/Ubuntu_Condensed/UbuntuCondensed-Regular.ttf
          weight: 400
    - family: UbuntuMono
      fonts:
        - asset: lib/fonts/Ubuntu_Mono/UbuntuMono-Regular.ttf
          weight: 400
    - family: Vollkorn
      fonts:
        - asset: lib/fonts/Vollkorn/Vollkorn-Regular.ttf
          weight: 400
    - family: VollkornSC
      fonts:
        - asset: lib/fonts/Vollkorn_SC/VollkornSC-Regular.ttf
          weight: 400
    - family: YesevaOne
      fonts:
        - asset: lib/fonts/Yeseva_One/YesevaOne-Regular.ttf
          weight: 400